### ISSUE TITLE
USER STORY User Vote

### ISSUE THREAD

**Issue by MattDunks94** [MattDunks94/my-first-agile-project#1]
In order to **give feedback** as a **user**, I can **vote for best time for running, best  track... etc**.

## Acceptance Criteria:
- User can select desired time.
- User can select their favourite location via map.
- Add search bar to find location.

## Tasks:
- [ ] For the 'best time for running' vote, include a time input.
- [ ] Embed google maps for the 'favourite location' vote.
- [ ] Add a location search bar above the embedded map.
